apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-configurj
rules:
  # Get/List Namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  # Get/Create/List/Delete Configmaps and Secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["list", "get", "create", "delete"]
  # Get/List globals.jnnkrdb.de
  - apiGroups: ["globals.jnnkrdb.de"]
    resources: ["globalsecrets", "globalconfigs"]
    verbs: ["get", "list"]