apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalsecrets.globals.jnnkrdb.de
spec:
  group: globals.jnnkrdb.de
  scope: Namespaced
  names:
    plural: globalsecrets
    singular: globalsecret
    kind: GlobalSecret
    shortNames: 
    - gs
    - gss
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # crds properties
              properties:
                immutable: 
                  type: boolean
                  default: false
                namespaces: 
                  type: object
                  properties:
                    avoidRegex:
                      type: array
                      items: 
                        type: string
                      default: []
                    matchRegex:
                      type: array
                      items: 
                        type: string
                      default: []
                name: 
                  type: string
                type: 
                  type: string
                  enum:
                    - Opaque
                    - kubernetes.io/service-account-token
                    - kubernetes.io/dockercfg
                    - kubernetes.io/dockerconfigjson
                    - kubernetes.io/basic-auth
                    - kubernetes.io/ssh-auth
                    - kubernetes.io/tls
                    - bootstrap.kubernetes.io/token
                data:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  default: {}
              required: [name, namespaces, type]