---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurj-operator
  namespace: configurj
  labels:
    app: configurj
    type: operator
spec:
  selector:
    matchLabels:
      app: configurj
      type: operator
  template:
    metadata:
      labels:
        app: configurj
        type: operator
    spec:
      serviceAccountName: configurj-sa
      containers:
      - name: configurj-operator
        image: docker.io/jnnkrdb/configurj-engine:latest
        imagePullPolicy: Always
        env:
          - name: LOGLEVEL
            value: "trace" # see in operator/engine/env/env.go -> LOGLEVEL
          - name: TIMEOUTSECONDS
            value: "30"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /healthz/live
            port: 80
          failureThreshold: 5
        readynessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /healthz/ready
            port: 80
          failureThreshold: 5