apiVersion: globals.jnnkrdb.de/v1alpha1
kind: GlobalSecret
metadata:
  name: gs-name
spec:
  immutable: false
  namespaces:
    avoidregex: []
    matchregex: []
  name: scrt-name
  type: Opaque # or other type, supported by kubernetes secrets
  data: {} # must be base64 encrypted by yourself
