apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalconfigs.globals.jnnkrdb.de
spec:
  group: globals.jnnkrdb.de
  scope: Namespaced
  names:
    plural: globalconfigs
    singular: globalconfig
    kind: GlobalConfig
    shortNames: 
    - gc
    - gcs
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # crds properties
              properties:
                immutable: 
                  type: boolean
                namespaces: 
                  type: array
                  items: 
                    type: string
                name: 
                  type: string
                data:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required: [active, namespaces, name, data]