apiVersion: v1
kind: ConfigMap
metadata:
  name: configurj-settings
  namespace: configurj
data:
  settings.json: |
    {
      "immutablereplicas":true,
      "healthport":"8080",
      "sourcenamespace":"global-configs",
      "avoidsecrets":[
        "default",
        "global-resources",
        "kube-node-lease",
        "kube-public",
        "kube-system"
      ],
      "avoidconfigmaps":[
        "default",
        "global-resources",
        "kube-node-lease",
        "kube-public",
        "kube-system"
      ]
    }
