apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalsecrets.globals.jnnkrdb.de
spec:
  group: globals.jnnkrdb.de
  scope: Namespaced
  names:
    plural: globalsecrets
    singular: globalsecret
    kind: GlobalSecret
    shortNames: 
    - gs
    - gss
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validation: 
                - rule: "self.type in ['Opaque','kubernetes.io/service-account-token','kubernetes.io/dockercfg','kubernetes.io/dockerconfigjson','kubernetes.io/basic-auth','kubernetes.io/ssh-auth','kubernetes.io/tls','bootstrap.kubernetes.io/token']"
                  message: "please use an existing secret.type -> https://kubernetes.io/docs/concepts/configuration/secret/#secret-types"
              # crds properties
              properties:
                immutable: 
                  type: boolean
                namespaces: 
                  type: array
                  items: 
                    type: string
                name: 
                  type: string
                type: 
                  type: string
                data:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required: [namespaces, name, data, type]