apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurj
  namespace: configurj
  labels:
    app: configurj
spec:
  selector:
    matchLabels:
      app: configurj
  template:
    metadata:
      labels:
        app: configurj
    spec:
      serviceAccountName: configurj-sa
      containers:
      - name: configurj-controller
        image: docker.io/jnnkrdb/configurj:v1-stable
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /livez
            # the port will be configured in the configmap -> settings.json
            port: 8080
          failureThreshold: 10
        volumeMounts:
          - name: settings
            mountPath: /configs
            readOnly: true
      volumes:
        - name: settings
          configMap:
            name: configurj-settings
